version: '3.8'

services:
  web1:
    image: httpd:2.4
    container_name: web1
    expose:
      - "80"
    volumes:
      - ./index1.html:/usr/local/apache2/htdocs/index.html
      - ./status.conf:/usr/local/apache2/conf/extra/status.conf
    networks:
      - monitoring_network

  web2:
    image: httpd:2.4
    container_name: web2
    expose:
      - "80"
    volumes:
      - ./index2.html:/usr/local/apache2/htdocs/index.html
      - ./status.conf:/usr/local/apache2/conf/extra/status.conf
    networks:
      - monitoring_network

  web3:
    image: httpd:2.4
    container_name: web3
    expose:
      - "80"
    volumes:
      - ./index3.html:/usr/local/apache2/htdocs/index.html
      - ./status.conf:/usr/local/apache2/conf/extra/status.conf
    networks:
      - monitoring_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Main entry point
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
      - web3
    networks:
      - monitoring_network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - "-nginx.scrape-uri=http://nginx/nginx_status"
    ports:
      - "9113:9113"
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge

